Fixes #68 Problems with csv export
patricklindsay/wice_grid pull request #69
Opened 2019-07-15 19:37 UTC by dima4p

2019-07-16 06:08 UTC, dima4p commented
There are 2 problems with the tests above:
1. `phantomjs` (not gem) is not installed on the testing machine.
2. Two failing specs
```
rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
```
fail on master too.

2020-01-29 10:58 UTC, kreintjes requested changes
@dima4p The specs you mention don't fail on master when I run all the specs locally (there are a lot of problems on Circle, but that seems to be specific to CircleCI and doesn't happen locally). I suspect your changes break the two specs you mention (one of them is also related to the CSV download link). Could you have a look at them and try to fix them?

Thanks for your PR!

2020-01-29 10:58 UTC, kreintjes commented on config/locales/nl.yml
> +    expand: Uitbreiden
Not sure about the other languages, but in Dutch this would be a better translation:
```suggestion
    expand: Uitklappen
```

2020-01-29 10:58 UTC, kreintjes commented on config/locales/nl.yml
> +    collapse: Ineenstorting
Not sure about the other languages, but in Dutch this would be a better translation:
```suggestion
    collapse: Inklappen
```

2020-01-29 11:48 UTC, dima4p commented on config/locales/nl.yml
> +    expand: Uitbreiden
thank you, I have fixed

2020-01-29 11:49 UTC, dima4p commented on config/locales/nl.yml
> +    collapse: Ineenstorting
thank you, I have fixed

2020-01-29 12:17 UTC, kreintjes commented
@dima4p thanks! Will you have a look at the failing spec(s) as well?

> ```
> rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
> rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> ```

(these do not fail on master on my machine locally)

2020-01-29 13:14 UTC, dima4p commented
> @dima4p thanks! Will you have a look at the failing spec(s) as well?
> 
> > ```
> > rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
> > rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> > ```
> 
> (these do not fail on master on my machine locally)

They do fail on my machine locally on upstream/master. Sorry.

2020-01-29 13:18 UTC, dima4p commented
> @dima4p thanks! Will you have a look at the failing spec(s) as well?
> 
> > ```
> > rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
> > rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> > ```
> 
> (these do not fail on master on my machine locally)

They do fail on my machine locally on upstream/master. Sorry.

> @dima4p thanks! Will you have a look at the failing spec(s) as well?
> 
> > ```
> > rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
> > rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> > ```
> 
> (these do not fail on master on my machine locally)



> @dima4p thanks! Will you have a look at the failing spec(s) as well?
> 
> > ```
> > rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
> > rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> > ```
> 
> (these do not fail on master on my machine locally)

ruby 2.6.3

2020-05-20 15:18 UTC, kreintjes commented
Hi Dima, I just tested your branch again, but 1 spec keeps failing while it does not on master (locally on my machine):

```
Failures:

  1) CSV export WiceGrid should export csv
     Failure/Error: expect(page).to have_content('ID;Title;Priority;Status;Project Name;')
       expected #has_content?("ID;Title;Priority;Status;Project Name;") to return true, got false
     # ./spec/features/csv_export_request_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 1 minute 52.23 seconds (files took 5.64 seconds to load)
224 examples, 1 failure

Failed examples:

rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
```

This seems related to the CSV export, so I do think it is broken because of your changes. Could you please have a look at it again? I'm using ruby 2.6.5p114.

2020-05-21 10:15 UTC, dima4p commented
> Hi Dima, I just tested your branch again, but 1 spec keeps failing while it does not on master (locally on my machine):
> 
> ```
> Failures:
> 
>   1) CSV export WiceGrid should export csv
>      Failure/Error: expect(page).to have_content('ID;Title;Priority;Status;Project Name;')
>        expected #has_content?("ID;Title;Priority;Status;Project Name;") to return true, got false
>      # ./spec/features/csv_export_request_spec.rb:11:in `block (2 levels) in <top (required)>'
> 
> Finished in 1 minute 52.23 seconds (files took 5.64 seconds to load)
> 224 examples, 1 failure
> 
> Failed examples:
> 
> rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
> ```
> 
> This seems related to the CSV export, so I do think it is broken because of your changes. Could you please have a look at it again? I'm using ruby 2.6.5p114.

I have also installed ruby 2.6.5p114 and at the commit c7a9da2a70 (that is patricklindsay:master] I have 2 failures:

```
Failures:

  1) auto reloads 3 WiceGrid should filter by Due Date independantly
     Failure/Error: expect(page).to have_content('2013-01-26')
       expected #has_content?("2013-01-26") to return true, got false
     # ./spec/features/auto_reloads3_request_spec.rb:100:in `block (3 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.6.5@github/gems/capybara-3.13.2/lib/capybara/session.rb:344:in `within'
     # /usr/local/rvm/gems/ruby-2.6.5@github/gems/capybara-3.13.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # /usr/local/rvm/gems/ruby-2.6.5@github/gems/capybara-3.13.2/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/features/auto_reloads3_request_spec.rb:99:in `block (2 levels) in <top (required)>'

  2) CSV export WiceGrid should export csv
     Failure/Error: expect(page).to have_content('ID;Title;Priority;Status;Project Name;')
       expected #has_content?("ID;Title;Priority;Status;Project Name;") to return true, got false
     # ./spec/features/csv_export_request_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 12.96 seconds (files took 2.93 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/features/auto_reloads3_request_spec.rb:74 # auto reloads 3 WiceGrid should filter by Due Date independantly
rspec ./spec/features/csv_export_request_spec.rb:9 # CSV export WiceGrid should export csv
```

2024-06-10 16:05 UTC, dima4p commented
I close this PR, as I did not expect it to appear here.

2024-06-10 16:05 UTC, closed without merging